spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: helpclosing-server-db.coy7ux4usksb.ap-northeast-2.rds.amazonaws.com
    username: root
    password: 20230603


  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        spatial:
          enabled: true


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace


jwt:
  secret:
    key: x!A%D*G-KaPdSgVkYp3s5v8y/B?E(H+M

cloud:
  aws:
    s3:
      bucket: helpclosing-bucket
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false
      credentials:
        access-key:
        secret-key: