spring:
  profiles:
    active: ${profile}
#server:
#  port: 80
#---
#spring:
#  profiles:
#    active: local
#server:
#  port: 8080
#---
#spring:
#  profiles:
#    active: prod
#server:
#  port: 8081